"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const controllers_1 = require("../controllers");
const router = (0, express_1.Router)();
router.post('/', controllers_1.createUser);
router.get('/', controllers_1.getUser);
router.get('/:id', controllers_1.getUserById);
router.put('/:id', controllers_1.updateUser);
router.delete('/:id', controllers_1.deleteUser);
exports.default = router;
