"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const controllers_1 = require("../controllers");
const router = (0, express_1.Router)();
router.post('/', controllers_1.createDeliverer);
router.get('/', controllers_1.getDeliverer);
router.get('/:id', controllers_1.getDelivererById);
router.put('/:id', controllers_1.updateDeliverer);
router.delete('/:id', controllers_1.deleteDeliverer);
exports.default = router;
