"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ClientModel = exports.CommandModel = exports.ChatModel = exports.DelivererModel = exports.UserModel = void 0;
var user_model_1 = require("./user.model");
Object.defineProperty(exports, "UserModel", { enumerable: true, get: function () { return user_model_1.UserModel; } });
var deliverer_model_1 = require("./deliverer.model");
Object.defineProperty(exports, "DelivererModel", { enumerable: true, get: function () { return deliverer_model_1.DelivererModel; } });
var chat_model_1 = require("./chat.model");
Object.defineProperty(exports, "ChatModel", { enumerable: true, get: function () { return chat_model_1.ChatModel; } });
var command_model_1 = require("./command.model");
Object.defineProperty(exports, "CommandModel", { enumerable: true, get: function () { return command_model_1.CommandModel; } });
var client_model_1 = require("./client.model");
Object.defineProperty(exports, "ClientModel", { enumerable: true, get: function () { return client_model_1.ClientModel; } });
